FROM python:3.11

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV PYTHONASYNCIODEBUG 1

RUN pip install --upgrade pip

RUN pip install poetry

COPY pyproject.toml ./
COPY poetry.lock ./

RUN poetry install

ENV PYTHONPATH=.

CMD [ "poetry", "run", "uvicorn", \
"--reload", \
"--host", "0.0.0.0", \
"--port", "8000", \
"app.main:app" \
]
