FROM python:3.11

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV PYTHONOPTIMIZE 1

RUN pip install --upgrade pip

RUN pip install poetry

COPY pyproject.toml ./
COPY poetry.lock ./

RUN poetry install --without dev

ENV PYTHONPATH=.

CMD [ "poetry", "run", "gunicorn", \
"-w", "2", \
"-k", "uvicorn.workers.UvicornWorker", \
"--bind", "0.0.0.0:8000", \
"app.main:app" \
]
